export const allAmenities = [
    { en: "Beach", es: "Playa" },
    { en: "Bed linens", es: "Ropa de cama" },
    { en: "Coffee maker", es: "Cafetera" },
    { en: "Cookware", es: "Utensilios de cocina" },
    { en: "Dining table", es: "Mesa de comedor" },
    { en: "Dishes and silverware", es: "Vajilla y cubertería" },
    { en: "Family/kid friendly", es: "Apto para familias/niños" },
    { en: "Free parking on street", es: "Aparcamiento gratuito en la calle" },
    { en: "Freezer", es: "Congelador" },
    { en: "Hair dryer", es: "Secador de pelo" },
    { en: "Hangers", es: "Perchas" },
    { en: "Hot water", es: "Agua caliente" },
    { en: "Internet", es: "Internet" },
    { en: "Iron", es: "Plancha" },
    { en: "Kitchen", es: "Cocina" },
    { en: "Luggage dropoff allowed", es: "Se permite dejar el equipaje" },
    { en: "Microwave", es: "Microondas" },
    { en: "Paid parking off premises", es: "Aparcamiento de pago fuera de las instalaciones" },
    { en: "Private entrance", es: "Entrada privada" },
    { en: "Refrigerator", es: "Refrigerador" },
    { en: "Stove", es: "Cocina" },
    { en: "TV", es: "TELEVISOR" },
    { en: "Towels provided", es: "Toallas incluidas" },
    { en: "Village", es: "Pueblo" },
    { en: "Washer", es: "Lavadora" },
    { en: "Wine glasses", es: "Copas de vino" },
    { en: "Pets allowed", es: "Se admiten mascotas" },
    { en: "Smoking allowed", es: "Se permite fumar" },
    { en: "Suitable for children (2-12 years)", es: "Apto para niños (2-12 años)" },
    { en: "Suitable for infants (under 2 years)", es: "Apto para bebés (menores de 2 años)" }
];
